[IV-23-23] Objetivo3
puchy22/nutri-app pull request #16
Opened 2023-10-28 18:26 UTC by puchy22

2023-11-02 10:00 UTC, puchy22 commented
@manuelvico0102 @Enaraque @javigp2002 @Morad02 Listo para revisión.

2023-11-02 11:53 UTC, javigp2002 approved these changes
:+1: La verdad que lo veo bastante bien y tu elección me parece muy adecuada. Yo también fuí a elegir `Bun` pero, a diferencia de ti, si me entró más miedo con el tiempo que lleva este en producción. ¡Mucho ánimo! 

Te he dejado unos comentarios que pueden ayudar un poco a embellecer el proyecto:sparkles:.

2023-11-02 11:53 UTC, javigp2002 commented on docs/gestor_dependencias.md
> +lo más interesante es usar elque viene integrado en Bun. Ya que así aprovechamos las claras
typo "elque"

2023-11-02 12:36 UTC, puchy22 commented
@JJ listo para revisión.

2023-11-02 12:47 UTC, JJ requested changes
Cada pieza por separado tiene sentido, pero el problema es que no has dejado claro cómo aplicas los criterios a las diferentes herramientas que has encontrado.

2023-11-02 12:47 UTC, JJ commented on docs/gestor_dependencias.md
> +Como gestores de dependencias tenemos varias opciones como *npm*, *yarn* o *pnmp*,
¿Cuales de los criterios objetivos mencionados anteriormente has usado aquí?

2023-11-02 12:47 UTC, JJ commented on docs/gestor_tareas.md
> +Bun run que es un comando integrado de Bun además de poder usarse para ejecutar archivos
Los criterios no sólo hay que listarlos, hay que seguirlos...

2023-11-03 17:42 UTC, puchy22 commented
@JJ Listo para revisión.

2023-11-03 18:03 UTC, JJ requested changes
Te quedaba un comentario, pero en esta revisión han surgido alguna cosa más. En todo caso, el problema de indicar primero los criterios y luego la elección sigue ahí.

2023-11-03 18:03 UTC, JJ commented on docs/gestor_tareas.md
> +Al final he decidico usar `bun run <script>` ya que al estar directamente integrado en el runtime
Si "estar integrado en el runtime" es tu criterio de elección, no tiene ningún sentido que listes otros que no lo estén. Una vez más, los criterios para elegir se establecen de antemano; los has listado arriba, di cuales estás usando en este caso.

2023-11-03 18:03 UTC, JJ commented on tsconfig.json
> +{
¿Necesitas esto con bun?

2023-11-03 18:03 UTC, JJ commented on tsconfig.json
> +    "jsx": "react-jsx",
¿Esto lo vas a usar? Si te lo genera automáticamente, convendría que usaras sólo las opciones que entiendas y que realmente vayas a usar.

2023-11-03 18:32 UTC, puchy22 commented on docs/gestor_dependencias.md
> +Como gestores de dependencias tenemos varias opciones como *npm*, *yarn* o *pnmp*,
Los acabo de comentar pero el commit no ha terminado de resolver la revisión

2023-11-03 18:42 UTC, JJ commented on docs/gestor_dependencias.md
> +Como gestores de dependencias tenemos varias opciones como *npm*, *yarn* o *pnmp*,
Si has hecho un cambio en otro lugar resuelve con el commit. En todo casi, aquí precisamente no listas el gestor de dependencias que efectivamente has usado.

2023-11-03 18:42 UTC, JJ commented on docs/gestor_tareas.md
> +Al final he decidico usar `bun run <script>` ya que al estar directamente integrado en el runtime
:arrow_up:

2023-11-03 18:44 UTC, puchy22 commented on tsconfig.json
> +{
Son [opciones sugeridas por la documentación oficial](https://bun.sh/docs/typescript), pero no son necesarias.

2023-11-03 19:09 UTC, puchy22 commented
@JJ Listo para revisión. Ya creo que he solucionado todos los problemas que me ha comentado para todos los archivos.

2023-11-03 19:15 UTC, JJ approved these changes
:+1: creo qeu tampoco va a mejorar mucho más; habría preferido que expresaras los criterios de una forma un poco más limpia, pero es ya una cuestión más pragmática que técnica.

2023-11-03 19:16 UTC, merged