[IV-23-23] Objetivo4
puchy22/nutri-app pull request #18
Opened 2023-11-08 19:03 UTC by puchy22

* [ ]  ¿Hay un camino claro que permita ir desde el código hasta la historia de
   usuario que desarrolla, pasando por el mensaje de commit y el issue
   correspondiente?
* [ ]  ¿Se ha intentado cubrir con tests una parte de la lógica de negocio que se
   esté desarrollando?
* [ ]  ¿Hay un producto mínimamente viable que describa lo que se va a entregar en
   este objetivo?
* [ ]  ¿En este producto mínimamente viable se han priorizado unas clases,
   módulos o paquetes más fundamentales frente a otros, movidos a otro
   PMV/Hito?
* [ ] ¿Estoy leyendo todo lo que marco o simplemente marco lo que se me pone por
delante?
* [ ] ¿Se han documentado las elecciones de biblioteca de aserciones y del
   de *test runner*?
* [ ] ¿Te has asegurado que lo que mencionas como biblioteca de aserciones y
test runners lo son realmente y tienen la misma funcionalidad? ¿O estás poniendo
`unittest` como *test runner* y `pytest` como biblioteca de aserciones?
* [ ] ¿Esa documentación incluye criterios de aceptación y también criterios de
búsqueda para las diferentes opciones?
* [ ]  ¿Se han seguido los principios F.I.R.S.T. en la creación del test y
   se ha documentado cómo se ha hecho?
* [ ]  ¿Se describe claramente en el PMV los tests que hay que pasar para que se
   considere viable?
* [ ] ¿Se han testeado también las excepciones?

2023-11-10 13:25 UTC, puchy22 commented
Listo para revisión @Morad02.

2023-11-12 16:21 UTC, Morad02 requested changes
Aparte de lo comentado,  revisa los issues para asignarles un milestone.

2023-11-12 16:21 UTC, Morad02 commented on src/compra.ts
Siguiendo la filosofía de código limpio y SRP (single responsibility principle). Una función solo debe encargarse de hacer una cosa y tiene que caber en un solo pantallazo. Viendo el constructor, vemos que no cumple con estos requisitos.

2023-11-12 16:21 UTC, Morad02 commented on test/extraccion.test.ts
Veo que estás comprobando que resultado sea igual a una salida esperada, pero que pasaría sí ahora cambias la lógica de negocio y no te saca los productos en el mismo orden.  Pues que no va a funcionar.

2023-11-17 19:19 UTC, puchy22 commented
@Morad02 Listo para revisión.

2023-11-18 10:05 UTC, Morad02 approved these changes

2023-11-18 10:44 UTC, puchy22 commented
@JJ Listo para revisión.

2023-11-18 10:48 UTC, puchy22 commented on docs/test_runner.md
Resuelto en [91fae22](https://github.com/puchy22/nutri-app/pull/18/commits/91fae22ca7e2a7ad21bb3616002179abf0536d5f)

2023-11-18 10:49 UTC, puchy22 commented on src/compra.ts
Resuelto en [ac4d2e6](https://github.com/puchy22/nutri-app/pull/18/commits/ac4d2e6b1f8a856babe6ad3023b025a49da7ba8b)

2023-11-18 10:51 UTC, puchy22 commented on test/extraccion.test.ts
Resuelto en [3e3b64d](https://github.com/puchy22/nutri-app/pull/18/commits/3e3b64dcade2fa9323b1c55808650ddb07024d79)

2023-11-18 11:06 UTC, JJ approved these changes
Qué queréis que os diga. Podría repasarlo y a lo mejor encontraría alguna cosa que mejorar, pero después de la revisión de @Morad02 sinceramente sería una falta de respeto a su trabajo. Así que sólo me queda agradecerle el trabajo comentado, y a ti @puchy22 haber reaccionado más rápidamente.
Si quieres que le eche algún vistazo al código más allá de la superación del objetivo, no tienes más que pedirlo, lo hago encantado, si quieres el jueves o viernes en clase.

2023-11-23 22:12 UTC, merged