[IV-23-24] Objetivo 1: Estructura general y planificación del proyecto
puchy22/nutri-app pull request #2
Opened 2023-09-21 15:49 UTC by puchy22

# Milestones

* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [x] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x] ¿El milestone 0 es mínimo *y* viable?
* [x] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [x] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?
    En mi opinión no veo mucha posibilidad entre los distintos milestones consecutivos
    para variar el desarrollo.

# HUs

* [x] ¿He tenido en cuenta en las historias de usuario que se trata de un
   proyecto que se desplegará en la nube?
* [x] ¿Están descritos todos los conceptos mencionados en las HUs con
   suficiente claridad, generalmente en documentos aparte?
   He descrito un poco a cada usuario en cada HU porque creo que el tema que el tema de la
   alimentación abarca un público tan amplio que no es necesario detallar a cada usuario.
* [x] ¿Tienen coherencia suficiente las historias de usuario, y en caso
   de que no lo tengan, se ha escrito un *user journey* para
   aclararlo?
   Creo que las HUs tienen las suficiente claridad como para entenderse simplemente
   con leerlas.
* [x] ¿Todas las historias de usuario representan un beneficio para el
    mismo y se relacionan con la lógica de negocio? Es decir, ¿los usuarios
    *desean* hacerlo o tú deseas que el usuario te lo pida para hacerlo?
    Las dos historias de usuario se tratan de problemas reales de los cuales tengo
    experiencia personal.

2023-09-25 12:03 UTC, JJ requested changes
Sería conveniente que lo revisara otra persona antes de que me lo envíes para una segunda ronda. Si @morad02 está disponible, le agradecería que le echara un vistazo; cuando esa persona lo apruebe me solicitas de nuevo revisión.

2023-09-25 12:03 UTC, JJ commented on docs/historias_usuario.md
> +realizar todas las cuentas y que simplemente me dijese "esta semana en tu compra te ha faltado proteína, podrías ir a comprar tanta
Tal como lo formulas, parece que es simplemente cuestión de almacenar y buscar. Si no hay un algoritmo de optimización claro es muy complicado que progrese hacia el objetivo 4.

Si se trata de aplicar un algoritmo de maximización con restricciones, sería conveniente que lo dijeras de la forma más explícita posible. También las diferentes circunstancias que indicas es posible que sean diferentes historias de usuario, en el sentido que lo que puedes estar maximizando son cosas diferentes.

2023-09-25 12:03 UTC, JJ commented on docs/milestones.md
> +- **M0**: Implementar el modelo del problema. Definiendo algún tipo de estructura de datos para almacenar los datos
¿Cómo puedes implementar el modelo del problema, si no tienes el modelo del problema?

2023-09-25 12:03 UTC, JJ commented on docs/milestones.md
> +- **M1**: Implementar una función que genere un reporte y una recomendación de la factura de la compra, en función
Los milestones no son tareas, son productos. Por favor, descríbelos como tales y qué los hace (o no) viables.

2023-09-25 13:23 UTC, Morad02 commented
Hola, seré tu revisor durante este objetivo. Cuando leas los comentarios del profesor y lo corrijas me avisas. Cualquier duda me escribes y intentaré ayudarte. Suerte!

2023-09-25 17:03 UTC, puchy22 commented
@Morad02 Listo para revisión.

2023-09-25 17:14 UTC, Morad02 approved these changes
La historia de usuario tiene suficiente contexto para modelizar el problema y los milestones son graduales y cumplen los requisitos. Por lo tanto, creo que está todo correcto. Avisa al profesor para que lo corrija.

2023-09-25 17:23 UTC, puchy22 commented
@JJ Listo para revisión.

2023-09-25 17:30 UTC, JJ requested changes
Por lo que estoy viendo en el milestone, la lógica de negocio que quieres implementar no es la que hay en la HU1, sino una previa que simplemente quiere ahorrarse tiempo tecleando todo lo que uno ha comprado en el supermercado.

Por favor, trata de especificar claramente cuales son los problemas que quieres resolver, y sobre todo que estén sincronizados los milestones y las HUs.

2023-09-25 17:30 UTC, JJ commented on docs/historias_usuario.md
> +compra para que la injesta de macro-nutrientes se acercase al máximo lo que en teoría tendría que consumir de media según el objetivo marcado.
OK, ¿quién diseña la primera compra? Si siempre vas a añadir o eliminar con respecto a la compra anterior, ¿cuál es la primera? ¿Tienes que añadirlo todo?

Si vas a añadir, ¿de dónde obtienes las posibles compras que vas a añadir?

2023-09-25 17:30 UTC, JJ commented on docs/milestones.md
> +del sumerpercado. En este se entregará el código fuente de este módulo y será viable si pasa los tests.
typo.

2023-09-26 18:44 UTC, JJ requested changes
Los detalles que te comento no bloquean el objetivo, sin embargo el problema es que realmente no has incluido ninguna HU que convierta lo que hay en la factura en nutrientes, calorías y lo que haga falta, con lo que realmente parece que no estás tratando de resolver el problema.

2023-09-26 18:44 UTC, JJ commented on docs/milestones.md
> +## [M0] Diseñar el modelo  del problema
¿Qué es *diseñar* un modelo? El modelo no se diseña, se construye a partir de las historias de usuario.

2023-09-26 18:44 UTC, JJ commented on docs/milestones.md
> +alimentos según las características(edad, peso y estatura) y hábitos físicos del usuario. En este se entregará el código fuente de este
Digo yo que teniendo las facturas habrá una forma más fácil de calcular esto.

2023-09-26 18:44 UTC, JJ commented on docs/milestones.md
> +El objetivo de este milestone es implementar un módulo que resuelva el problema de optimizar la agregación de alimentos en función de
Por favor, no insistáis en "implementar módulos". Puede que haya que implementar módulos, módulo o a saber qué, una función sólo en un módulo existente. Simplemente dejad claro que lo que hacer es que la lógica necesaria para una HU determinada funcione.

2023-09-26 18:44 UTC, JJ commented on docs/milestones.md
> +En este se entragará el código fuente del módulo y será viable si se pasan los tests.
typo

2023-09-27 10:58 UTC, puchy22 commented on docs/milestones.md
> +alimentos según las características(edad, peso y estatura) y hábitos físicos del usuario. En este se entregará el código fuente de este
No entiendo muy bien la manera "más fácil", he cambiado para que en lugar de hacerlo en función de los alimentos directamente se haga de la suma de los distintos macronutrientes extraídos del M1. Pero lo que siempre hay que tener en cuenta son las características físicas y hábitos porque no puede durar lo mismo la misma compra para una mujer de 50 años que pesa 50 kg; que para un hombre de 22 años que mida 1,90 y pese 90kg.

2023-09-27 11:02 UTC, puchy22 commented
@JJ. Listo para revisión. He añadido una historia de usuario y creo que ahora todos los milestones están en relación con las historias de usuario; además he cambiado para no incluir que los milestones sean "implementar función, módulo o clase".

2023-09-27 11:46 UTC, JJ commented on docs/milestones.md
> +alimentos según las características(edad, peso y estatura) y hábitos físicos del usuario. En este se entregará el código fuente de este
Si suponemos que la compra es individual, y uno compra unos yogures de proteínas un día, y luego 7 días más tarde, la diferencia de fechas (extraída de la factura) te dirá cuanto tiempo se suele emplear en consumir una serie de alimentos, ¿no?
Si lo quieres hacer con los macronutrientes... Complicado, porque pueden provenir de diferentes fuentes, y no sabes cuantos está gastando cada día, salvo que pidas cada día qué se está comiendo, en cuyo caso estás pidiendo muchos datos al usuario y no sería adecuado aquí.
En todo caso, siendo el milestone 2 tampoco me preocupa demasiado, sólo quería que te dieras cuenta de lo que implica cada cosa. También ten en cuenta que a partir de milestone 1 tendrás que implementar otra serie de cosas y publicarlas, todo ello antes de pasar a este M2.

2023-09-27 11:57 UTC, JJ approved these changes
:+1:

2023-09-27 11:57 UTC, JJ commented on docs/historias_usuario.md
> +Ojalá existiera una solución que, solo con pasarle la factura electrónica de la compra, me proporcionara un total de todos
Buen uso del "ojalá"

2023-09-28 06:35 UTC, merged