[IV 23-24] Objetivo 6
puchy22/nutri-app pull request #56
Opened 2023-12-01 13:08 UTC by puchy22

* [ ] ¿Se han establecido criterios *a priori* para elegir el sistema de
integración continua más conveniente y se han calificado los sistemas que
cumplan esos requisitos según esos criterios?
* [ ] ¿Se han examinado varios sistemas de integración continua?
* [ ] ¿Se han configurado varios sistemas de integración continua?
* [ ] ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [ ] ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   dellenguaje con las que funciona correctamente nuestra aplicación?
* [ ] ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?
* [ ] ¿Se han justificado correctamente las versiones del lenguaje que se están
testeando y se ha comprobado que no se comprueban varias veces lo mismo (la
misma versión en CI y en el contenedor Docker en otro sistema CI?

2023-12-28 15:31 UTC, puchy22 commented
@PabloBarTo @javigp2002 @danieeeld2 @carlotiii30 @manuelvico0102 Listo para revisión.

2023-12-28 17:48 UTC, carlotiii30 reviewed
Buenas! Antes de nada, feliz navidad. Te he dejado un par de comentarios para que revises, espero que sean de ayuda.

2023-12-28 17:48 UTC, carlotiii30 commented on docs/ci_tool.md
> +de Docker con
Creo que esta frase está incompleta. Por favor, corrígela.

2023-12-28 17:48 UTC, carlotiii30 commented on .github/workflows/bun_canary_test.yml
> +          bun-version: canary
Creo que deberías probar más de una versión, algo como la antigua y la actual, o en desarrollo. No una única versión.

2023-12-29 10:56 UTC, puchy22 commented on .github/workflows/bun_canary_test.yml
> +          bun-version: canary
El problema con bun es que es tan reciente que no versión LTS, estable o dev como otros runtimes más antiguos como Node. Por eso con el GitHub Actions pruebo la versión canary y la del contenedor que es la latest. Aún así voy a documentarlo mejor en el docs.

2023-12-29 11:08 UTC, carlotiii30 commented
👍🏻 Gracias por la aclaración, lo veo listo.

2023-12-29 11:12 UTC, puchy22 commented
Hola @carlotiii30, lo primero es feliz navidad :santa: igualmente. Ya he corregido y aclarado lo que me has dicho. Listo para revisión.

2023-12-29 14:49 UTC, puchy22 commented
@JJ Listo para revisión.

2023-12-29 17:34 UTC, JJ requested changes
Muchas gracias a @carlotiii30 por la revisión, que parece razonable. Aparte, si no usas alguna versión pre-1.0 estás testeando dos sistemas de CI con lo mismo, el contenedor. El objetivo de probar diferentes sistemas, conseguido, pero el por qué se prueban diferentes sistemas (probar diferentes versiones en paralelo) no tanto.

2023-12-29 17:34 UTC, JJ commented on .github/workflows/bun_canary_test.yml
> +          bun-version: canary
Me parece razonable lo que dice @carlotiii30 . Aunque bun no tenga una política LTS, sí es cierto que sacó la 1.0 prácticamente antes de ayer y es posible que haya todavía que soportar la 0.x. Aunque no funcione con el código que estás usando, convendría que la hubieras probado; si no funciona, lo documentas y listo.

2023-12-29 22:57 UTC, puchy22 commented
@JJ Ya he añadido y documentado las pruebas con la versión 0.8 y funciona todo correctamente. Listo para revisión.

2023-12-30 07:50 UTC, JJ reviewed
DRY también se puede aplicar a los flujos de trabajo de CI. Por eso existe en casi todos ellos una [*matrix*](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs), que te permite usar un solo workflow con valores variables en la versión o en otras cosas (como el sistema operativo). Échale un vistazo, por favor.

2023-12-30 10:40 UTC, puchy22 commented
@JJ, cierto no había caído en que estaba repitiendo código, ya esta solucionado. Listo para revisión.

2023-12-31 08:58 UTC, JJ approved these changes
:+1:

2023-12-31 14:17 UTC, merged