[IV-23-24] Objetivo 2
puchy22/nutri-app pull request #7
Opened 2023-10-05 07:34 UTC by LuciaAnsino

Por consenso hemos decidido el lenguaje en el #6 closes #6

2023-10-19 21:15 UTC, puchy22 requested changes

2023-10-19 21:15 UTC, puchy22 commented on src/producto.js
> +exports.Producto = Producto;
Creo que este archivo es una transpilación de TypeScript a JavaScript, creo que estos archivos que son de ejecución productos de la transpilación y no deberían estar en GitHub; deberían estar incluidos en el gitignore para que no se subiesen.

2023-10-19 21:15 UTC, puchy22 commented on src/producto.ts
> +    private _grasas: number;
Creo que podría ser interesante estos atributos declararlos como readonly en lugar de privados, ya que los valores nutricionales de un alimento desde que se cree el objeto nunca van a cambiar, por lo que solo te interesa leer su valor.

2023-10-19 21:15 UTC, puchy22 commented on src/ticket.js
> +exports.Compra = Compra;
Lo mismo para este archivo JS.

2023-10-20 07:27 UTC, LuciaAnsino commented
@puchy22 Ya he realizado los cambios oportunos

2023-10-20 13:59 UTC, puchy22 commented
@LuciaAnsino Ya lo veo bien, creo que está listo para que lo revise @JJ.

2023-10-20 13:59 UTC, puchy22 approved these changes

2023-10-23 09:38 UTC, LuciaAnsino commented
@JJ listo para revisión

2023-10-23 09:46 UTC, JJ commented on src/compra.ts
> +    readonly compra: [Producto,number][];
Si siempre van juntos, ¿has considerado la posibilidad de convertirlo en un tipo o en una clase?

2023-10-26 06:53 UTC, merged